name: 'Intelligent DevOps (Intelli-Ops) using Azure OpenAI'
description: 'AI-powered GitHub Action for code reviews, PR descriptions, unit tests, and issue management using Amazon Bedrock.'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  azure-openai-api-key:
    description: 'Azure OpenAI API key'
    required: true
  azure-openai-endpoint:
    description: 'Azure OpenAI endpoint'
    required: true
  azure-openai-version:
    description: 'Azure OpenAI version'
    required: true
    default: '2023-05-15'
  azure-openai-deployment:
    description: 'Azure OpenAI deployment'
    required: true
  azure-openai-temperature:
    description: 'Azure OpenAI temperature'
    required: false
    default: '0.7'
  generate-code-review-exclude-files:
    description: 'Exclude file list, separated by comma, e.g. [*.md,*.json]'
    required: false
    # default to null to disable the filter
    default: ''
  generate-code-review-level:
    description: 'Code review level'
    required: false
    default: 'detailed'
  generate-code-review:
    description: 'Generate code review'
    required: false
  generate-pr-description:
    description: 'Generate PR description'
    required: false
    default: 'false'
  generate-unit-test:
    description: 'Whether to generate unit tests'
    required: false
    default: 'false'
  generate-unit-test-source-folder:
    description: 'The folder path where unit tests should be generated based on the source code, only applicable when generate-unit-test is true'
    required: false
    default: ''
  generate-unit-test-exclude-files:
    description: 'Exclude file list, separated by comma, e.g. [*.md,*.json]'
    required: false
    default: ''
  output-language:
    description: 'Output language'
    required: false
    default: 'en'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  color: 'purple'
  icon: 'check-circle'
